wandb: WARNING Calling wandb.run.save without any arguments is deprecated.Changes to attributes are automatically persisted.
c:\Users\ddc4k\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
wandb: WARNING The save_model argument by default saves the model in the HDF5 format that cannot save custom objects like subclassed models and custom layers. This behavior will be deprecated in a future release in favor of the SavedModel format. Meanwhile, the HDF5 model is saved as W&B files and the SavedModel as W&B Artifacts.
Traceback (most recent call last):
  File "c:\Users\ddc4k\OneDrive\Desktop\빅브라더\sample\sample2.py", line 79, in <module>
    history = model.fit(train_dataset, epochs=epochs, callbacks=[
  File "c:\Users\ddc4k\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "c:\Users\ddc4k\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\integration\keras\keras.py", line 555, in set_model
    self.model = model
AttributeError: can't set attribute 'model'