wandb: WARNING Calling wandb.run.save without any arguments is deprecated.Changes to attributes are automatically persisted.
Traceback (most recent call last):
  File "c:\Users\ddc4k\OneDrive\Desktop\빅브라더\sample\ensemble_sample.py", line 122, in <module>
    unknown_train, unknown_test, scalar) = prepare_data(csv_file)
  File "c:\Users\ddc4k\OneDrive\Desktop\빅브라더\sample\ensemble_sample.py", line 23, in prepare_data
    selected_features = all_data.drop(
  File "c:\Users\ddc4k\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ddc4k\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\frame.py", line 4956, in drop
    return super().drop(
  File "c:\Users\ddc4k\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\generic.py", line 4279, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "c:\Users\ddc4k\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\generic.py", line 4323, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "c:\Users\ddc4k\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\base.py", line 6644, in drop
    raise KeyError(f"{list(labels[mask])} not found in axis")
KeyError: "['품명'] not found in axis"